version: '3'
services:
  app:
    build: .
    ports:
      - "8180:8181"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/transactions
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
